### ISSUE TITLE
About the code implement of name_methods 

### ISSUE THREAD

**Issue by Sharpiless** [CAMP-eXplain-AI/PathwayGrad#1]
name_methods = ["CDRP", "NC", "IntGrad", "GreedyNC", "Random", "CDRP-R"]

Is the list in the correct order? 

Because the X-axis list used to draw in plots is:

['NeuronIntGrad', 'vs. NeuronMCT', 'vs. DGR(init=1)', 'vs. DGR(init=r)', 'vs. GreedyPruning', 'vs. RandomPruning']

Maybe it should be: name_methods = ["IntGrad", "NC", "CDRP", "CDRP-R", "GreedyNC", "Random"]

**Comment by Sharpiless** [comment]
I adjusted the order and got the following result on CIFAR-100 dataset:

![在这里插入图片描述](https://img-blog.csdnimg.cn/9b0fec2937ca42738266b414c4c1d96d.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NDkzNjg4OQ==,size_16,color_FFFFFF,t_70#pic_center)
![在这里插入图片描述](https://img-blog.csdnimg.cn/d2d097a7537d4994a96ecfb34cbc93f2.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NDkzNjg4OQ==,size_16,color_FFFFFF,t_70#pic_center)

![在这里插入图片描述](https://img-blog.csdnimg.cn/6ac1514728c3456a9cbf394533017789.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NDkzNjg4OQ==,size_16,color_FFFFFF,t_70#pic_center)
![在这里插入图片描述](https://img-blog.csdnimg.cn/a652556af86a471c9ba2c54ce5c7f911.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3dlaXhpbl80NDkzNjg4OQ==,size_16,color_FFFFFF,t_70#pic_center)

**Comment by Soroosh-Bsl** [comment]
Hi @Sharpiless,

Thank you for sharing your concern.

I believe there is a misunderstanding of the code in what you have reported. 
Kindly note Line:13 and Line:44 and Lines:329-334 and Line:368 of `plots.py`, in which we have reorganized the loaded array into the correct order. 
Hence, the results of the paper are valid and true. And your commented plots are not.

Do not hesitate to ask if you have any further questions or you think the committed code might have slight errors. I can check with the original code and let you know the result. 

Many thanks.

**Comment by Sharpiless** [comment]
Thank you very much for your reply. There are no more questions. Thank you for your work.
